### PR TITLE
Add current version of BTreeMap unit tests

### PR DESCRIPTION
**Pull request by ssomers**
If you want it, a big test program bundling all BTreeMap unit test cases, except those involving panic and Vec::sor

### CODE REVIEW

**Comment by RalfJung** [comment]
Thanks! However, I am not sure if we should duplicate all these tests on the Miri side. Does this cover anything that https://github.com/RalfJung/miri-test-libstd would not already cover?

**Comment by ssomers** [comment]
Obviously not, but I understand this is currently the only way to cover them with -Zmiri-track-raw-pointers, and I assumed this branch won't last long.

**Comment by RalfJung** [comment]
This branch is part of a [PR](https://github.com/rust-lang/miri/pull/1614), I plan to merge it once https://github.com/rust-lang/rust/pull/78597 lands.

> Obviously not, but I understand this is currently the only way to cover them with -Zmiri-track-raw-pointers, and I assumed this branch won't last long.

You can set custom flags with https://github.com/RalfJung/miri-test-libstd through the `MIRIFLAGS` env var. You might have to also set a test suite filter to only run btree tests. And you'll probably need latest rustc master to fix some issues I found in other parts of the standard library. But then I think this should work.

**Comment by RalfJung** [comment]
The latest nightly via rsutup should install a Miri that supports the flag that also has the required stdlib fixes, so you should be able to use it for this purpose.

**Comment by RalfJung** [comment]
Hm, that does not actually work as there seem to be int-ptr-casts soemwhere in argument parsing...
```
$ MIRIFLAGS=-Zmiri-track-raw-pointers ./run-test.sh alloc btree
[...]
error: Undefined Behavior: no item granting read access to tag <untagged> at alloc2709 found in borrow stack.
   --> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/args.rs:146:47
    |
146 |                     let cstr = CStr::from_ptr(*argv.offset(i) as *const libc::c_char);
    |                                               ^^^^^^^^^^^^^^^ no item granting read access to tag <untagged> at alloc2709 found in borrow stack.
    |
    = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
    = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
            
    = note: inside closure at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/args.rs:146:47
    = note: inside closure at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:905:28
    = note: inside `<core::ops::Range<isize> as core::iter::Iterator>::fold::<(), [closure@core::iter::adapters::map_fold<isize, std::ffi::OsString, (), [closure@std::sys::unix::args::imp::clone::{closure#0}], [closure@core::iter::Iterator::for_each::call<std::ffi::OsString, [closure@<std::vec::Vec<std::ffi::OsString> as std::vec::SpecExtend<std::ffi::OsString, core::iter::Map<core::ops::Range<isize>, [closure@std::sys::unix::args::imp::clone::{closure#0}]>>>::spec_extend::{closure#0}]>::{closure#0}]>::{closure#0}]>` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2023:21
    = note: inside `<core::iter::Map<core::ops::Range<isize>, [closure@std::sys::unix::args::imp::clone::{closure#0}]> as core::iter::Iterator>::fold::<(), [closure@core::iter::Iterator::for_each::call<std::ffi::OsString, [closure@<std::vec::Vec<std::ffi::OsString> as std::vec::SpecExtend<std::ffi::OsString, core::iter::Map<core::ops::Range<isize>, [closure@std::sys::unix::args::imp::clone::{closure#0}]>>>::spec_extend::{closure#0}]>::{closure#0}]>` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:945:9
    = note: inside `<core::iter::Map<core::ops::Range<isize>, [closure@std::sys::unix::args::imp::clone::{closure#0}]> as core::iter::Iterator>::for_each::<[closure@<std::vec::Vec<std::ffi::OsString> as std::vec::SpecExtend<std::ffi::OsString, core::iter::Map<core::ops::Range<isize>, [closure@std::sys::unix::args::imp::clone::{closure#0}]>>>::spec_extend::{closure#0}]>` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678:9
    = note: inside `<std::vec::Vec<std::ffi::OsString> as std::vec::SpecExtend<std::ffi::OsString, core::iter::Map<core::ops::Range<isize>, [closure@std::sys::unix::args::imp::clone::{closure#0}]>>>::spec_extend` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/vec.rs:2337:17
    = note: inside `<std::vec::Vec<std::ffi::OsString> as std::vec::SpecFromIterNested<std::ffi::OsString, core::iter::Map<core::ops::Range<isize>, [closure@std::sys::unix::args::imp::clone::{closure#0}]>>>::from_iter` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/vec.rs:2109:9
    = note: inside `<std::vec::Vec<std::ffi::OsString> as std::vec::SpecFromIter<std::ffi::OsString, core::iter::Map<core::ops::Range<isize>, [closure@std::sys::unix::args::imp::clone::{closure#0}]>>>::from_iter` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/vec.rs:2119:9
    = note: inside `<std::vec::Vec<std::ffi::OsString> as core::iter::FromIterator<std::ffi::OsString>>::from_iter::<core::iter::Map<core::ops::Range<isize>, [closure@std::sys::unix::args::imp::clone::{closure#0}]>>` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/alloc/src/vec.rs:1959:9
    = note: inside `<core::iter::Map<core::ops::Range<isize>, [closure@std::sys::unix::args::imp::clone::{closure#0}]> as core::iter::Iterator>::collect::<std::vec::Vec<std::ffi::OsString>>` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
    = note: inside `std::sys::unix::args::imp::clone` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/args.rs:144:13
    = note: inside `std::sys::unix::args::imp::args` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/args.rs:136:22
    = note: inside `std::sys::unix::args::args` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/args.rs:24:5
    = note: inside `std::env::args_os` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/env.rs:759:21
    = note: inside `std::env::args` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/env.rs:732:19
    = note: inside `test::test_main_static` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/library/test/src/lib.rs:139:16
    = note: inside `main`
```

**Comment by RalfJung** [comment]
Ah, things are going through an `AtomicPtr`... so https://github.com/rust-lang/rust/pull/77611 (or its successor) should help with this.

**Comment by ssomers** [comment]
> The latest nightly via rsutup should install a Miri

I didn't notice rustup was stuck on rustfmt and not on miri. That makes life a lot easier… once we get that `AtomicPtr` to play ball.

**Pull request closed without merging**
